const categories = [
  "Action",
  "Adventure",
  "Animation",
  "Art & Design",
  "Business & Finance",
  "Cars & Automobiles",
  "Comedy",
  "DIY & Crafts",
  "Documentary",
  "Drama",
  "Education",
  "Entertainment",
  "Fashion & Beauty",
  "Fitness",
  "Food & Cooking",
  "Gaming",
  "Health",
  "History & Culture",
  "Horror",
  "Kids & Family",
  "Lifestyle",
  "Motivation & Self-Help",
  "Music",
  "Mystery / Thriller",
  "News & Politics",
  "Podcasts & Talk Shows",
  "Reaction",
  "Review (Products, Movies, Tech)",
  "Romance",
  "Sci-Fi",
  "Science & Nature",
  "Short Film",
  "Spirituality & Religion",
  "Sports",
  "Technology",
  "Travel",
  "Tutorial / How-to",
  "Vlog",
];
